### ISSUE TITLE
Error: No such container:path: aging/chemtreemap:/examples

### ISSUE THREAD

**Issue by hjzhang1018** [ajing/ChemTreeMap#3]
I was following instructions at “acing.github.io/ChemTreeMap”, however I encountered several issues.

1. When I tried to import my own dataset file into the docker container using command “ `docker cp foo.txt ajing/chemtreemap:/examples/foo.txt`”, an error message said that “Error: No such container:path: aging/chemtreemap:/examples”. I wonder if there are any steps missing?

2. The instructions suggest to change examples.py accordingly, but I wonder if I could change this py file directly in your repository “aging/chemtreemap” or do I need to create a personal repository forked from “aging/chemtreemap”? If so, I need to create an independent docker hub repository as well. Also I need to make builds to GitHub repository but they need to provide the Dockerfile path. I searched for this Dockerfile but couldn't find it.

Please forgive me for these idiot questions but I am really a newbie for bioinformatics. I would be very appreciative if you could please help me with these problems. Thank you.

**Comment by ajing** [comment]
sorry for my late message.

1. you may want to first start the docker container by `docker run -t -i -p 8000:8000 ajing/chemtreemap /bin/bash`, and leave it open. then open another terminal and run the docker cp command
2. you can replace any of the files in examples (i.e. aff.txt), then you don't need to change the example.py file.

Thanks
